INSERT INTO university(faculty) VALUES('Angola');
INSERT INTO university(faculty) VALUES('Fiji');
INSERT INTO university(faculty) VALUES('Faroe Islands');
INSERT INTO university(faculty) VALUES('Timor-Leste');
INSERT INTO university(faculty) VALUES('Saint Vincent and the Grenadines');
INSERT INTO from_city(city) VALUES('Acevedostad');
INSERT INTO from_city(city) VALUES('Lake Darrellchester');
INSERT INTO from_city(city) VALUES('Kimberg');
INSERT INTO from_city(city) VALUES('North Colleen');
INSERT INTO from_city(city) VALUES('New Amy');
INSERT INTO from_city(city) VALUES('Lake Robertfort');
INSERT INTO from_city(city) VALUES('Davidview');
INSERT INTO classman(name, age, university_id, city_id) VALUES('Stephanie Smith', 21, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Stephanie Mack', 23, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jocelyn Perez', 21, 5, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Kirsten Turner', 24, 2, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Mrs. Heather Hunt', 21, 5, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Charles Martinez', 21, 3, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Mark Baker', 19, 3, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Timothy Cole', 22, 4, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Madeline Boone', 23, 5, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Christian Ramirez', 21, 4, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Tracy Kirby', 18, 5, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Noah Perry', 24, 5, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jordan Garcia', 19, 1, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('George Moss', 19, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Joseph Mason', 18, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Audrey Barber DDS', 19, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Sabrina Hall', 18, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Rachel Miller', 21, 1, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Steven Frazier', 18, 1, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Tiffany Harris', 24, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Cynthia Lopez', 24, 2, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Benjamin Collins', 22, 5, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jennifer Chapman', 21, 5, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Reginald Cole', 20, 3, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Bobby Lloyd', 24, 5, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Paul Harris', 22, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Becky Harrison', 19, 1, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Austin Riley', 20, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Robert Santos', 18, 2, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Mrs. Christina Waters', 21, 5, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Stephen Lawrence', 20, 2, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Amanda Blair', 18, 5, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Charlene Evans', 20, 4, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Heather Stephens', 23, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Michael Bird', 22, 4, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Christopher Hill', 21, 1, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Michelle Anderson', 18, 1, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Christian Wang', 25, 3, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Michelle Arnold', 19, 2, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('James Proctor', 22, 4, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Rachel Hill', 19, 2, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Anthony Herring', 19, 2, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Darlene Savage', 20, 3, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jamie Davis', 21, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Cody Rodriguez', 23, 3, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jason Aguilar', 18, 3, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Gloria Chapman', 25, 4, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Brittany Thomas', 18, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Douglas Hanson', 23, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Garrett Hicks', 18, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Mr. David Carter', 19, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Monica Kelley', 22, 5, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Abigail Atkinson', 24, 2, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Scott Melton', 21, 5, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Amber Glover', 19, 3, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Diana Cole', 21, 2, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Christopher Hayden', 23, 4, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Laura Woods', 22, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Brenda Turner', 21, 1, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Victoria Hill', 22, 2, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Kevin Lane', 18, 1, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Justin Chapman', 21, 2, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Nicole Johnson', 25, 4, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Desiree Reed', 25, 5, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Vincent Lloyd', 22, 3, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Mrs. Linda Vance', 18, 1, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Elizabeth Brown', 24, 1, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Troy Ramirez', 20, 5, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jeffrey Patel', 25, 4, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Taylor Ross', 19, 5, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Steven Griffin', 21, 1, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('James Conrad', 22, 4, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Spencer Martin', 21, 2, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Marie Gray', 22, 5, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jordan Chapman', 25, 3, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Maria Adams', 21, 4, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Shane Hall', 18, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('David Willis', 19, 5, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jeffrey Harper', 23, 4, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Erica Adams', 25, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Joseph Gonzales', 20, 5, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Angela Johnson', 19, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Michael Owens', 23, 5, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Nicole Wilson', 23, 4, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Robert Johns', 20, 5, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Ronald Chang', 24, 4, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Melissa Kirk', 24, 2, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Aaron Phillips', 21, 3, 4);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Lisa Rodriguez', 19, 4, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jorge Ball', 21, 2, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Dana Clay', 24, 5, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Erika Brown', 18, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Victoria Sullivan', 22, 5, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Elizabeth Jackson', 25, 3, 2);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Dorothy Esparza', 22, 3, 1);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Cameron Hill', 24, 1, 6);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Gabrielle Roberts', 18, 2, 7);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Jesse Benton', 21, 5, 5);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Todd Cox', 18, 1, 3);
INSERT INTO classman(name, age, university_id, city_id) VALUES('Ronald Baker', 23, 2, 5);